application:
  environment: ${ENVIRONMENT:local}
  queues:
    placement-synced: ${PLACEMENT_SYNCED_QUEUE:http://localstack:4566/000000000000/tis-trainee-sync-local-record}
    programme-membership-synced: ${PROGRAMME_MEMBERSHIP_SYNCED_QUEUE:http://localstack:4566/000000000000/tis-trainee-sync-local-programme-membership}
  sns:
    arn: ${ACTION_UPDATE_TOPIC:arn:aws:sns:eu-west-2:000000000000:tis-trainee-actions-event}
    message-attribute: ACTION

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

server:
  port: 8212
  servlet:
    context-path: /actions

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

spring:
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566/}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:pwd}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:actions}?authSource=admin
