application:
  environment: ${ENVIRONMENT:local}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

server:
  port: 8212
  servlet:
    context-path: /actions

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}
