application:
  environment: ${ENVIRONMENT:local}
  queues:
    placement-synced: ${PLACEMENT_SYNCED_QUEUE}
    programme-membership-synced: ${PROGRAMME_MEMBERSHIP_SYNCED_QUEUE}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

server:
  port: 8212
  servlet:
    context-path: /actions

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

spring:
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:pwd}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:actions}?authSource=admin
