application:
  queues:
    account-confirmed: dummy
    placement-synced: dummy
    programme-membership-synced: dummy
  sns:
    arn: dummy

mongock:
  enabled: false

spring:
  cloud:
    aws:
      sqs:
        enabled: false
